name: Build, Test and Lint
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
    pull_request:
        types: [opened, reopened, synchronize]
        branches:
            - main
            - release/integrate_0713

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    circuits-test:
        name: Circuits
        uses: ./.github/workflows/build-and-test.yml
        with:
          target: "circuits"
        secrets:
          CR_PAT: ${{ secrets.CR_PAT }}

    contracts-test:
        name: Contracts
        uses: ./.github/workflows/build-and-test.yml
        with:
          target: "contracts"
        secrets:
          CR_PAT: ${{ secrets.CR_PAT }}

    relay-test:
        name: Relay
        uses: ./.github/workflows/build-and-test.yml
        with:
          target: "relay"
        secrets:
          CR_PAT: ${{ secrets.CR_PAT }}
    
    frontend-test:
        name: Frontend
        uses: ./.github/workflows/build-and-test.yml
        with:
          target: "frontend"
        secrets:
          CR_PAT: ${{ secrets.CR_PAT }}

    lint:
        name: Lint
        runs-on: ubuntu-22.04
        timeout-minutes: 10
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Install node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16'
            - name: Install packages
              run: yarn
            - name: Lint
              run: |
                  yarn lint:fix
                  yarn lint:check
