name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
    pull_request:
        types: [opened, reopened, synchronize]
        branches:
            - main
            - release/integrate_0713

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    circuits-test:
        name: Circuits Test
        runs-on: ubuntu-22.04
        container:
            image: ghcr.io/jason-ntu/ubuntu-22.04:circom
            credentials:
                username: jason-ntu
                password: ${{ secrets.CR_PAT }}
        timeout-minutes: 15
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Install node.js
              uses: actions/setup-node@v3
              with:
                node-version: '16'
            - name: Modify system variable PATH
              run: echo "/root/.cargo/bin" >> $GITHUB_PATH
            - name: Install yarn
              run: npm install --global yarn
            - name: Install packages
              run: yarn
            - name: Build
              run: yarn build
            - name: Test
              run: yarn circuits test

    contracts-test:
        name: Contracts Test
        runs-on: ubuntu-22.04
        container:
            image: ghcr.io/jason-ntu/ubuntu-22.04:circom
            credentials:
                username: jason-ntu
                password: ${{ secrets.CR_PAT }}
        timeout-minutes: 15
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Install node.js
              uses: actions/setup-node@v3
              with:
                node-version: '16'
            - name: Modify system variable PATH
              shell: bash
              run: echo "/root/.cargo/bin" >> $GITHUB_PATH
            - name: Install yarn
              run: npm install --global yarn
            - name: Install packages
              run: yarn
            - name: Build
              run: yarn build
            - name: Test
              run: yarn contracts test

    relay-test:
        name: Relay Test
        runs-on: ubuntu-22.04
        container:
            image: ghcr.io/jason-ntu/ubuntu-22.04:circom
            credentials:
                username: jason-ntu
                password: ${{ secrets.CR_PAT }}
        timeout-minutes: 15
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Install node.js
              uses: actions/setup-node@v3
              with:
                node-version: '16'
            - name: Modify system variable PATH
              shell: bash
              run: echo "/root/.cargo/bin" >> $GITHUB_PATH
            - name: Install yarn
              run: npm install --global yarn
            - name: Install packages
              run: yarn
            - name: Build
              run: yarn build
            - name: Test
              run: yarn relay test

    frontend-test:
        name: Frontend Test
        runs-on: ubuntu-22.04
        container:
            image: ghcr.io/jason-ntu/ubuntu-22.04:circom
            credentials:
                username: jason-ntu
                password: ${{ secrets.CR_PAT }}
        timeout-minutes: 15
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Install node.js
              uses: actions/setup-node@v3
              with:
                node-version: '16'
            - name: Modify system variable PATH
              shell: bash
              run: echo "/root/.cargo/bin" >> $GITHUB_PATH
            - name: Install yarn
              run: npm install --global yarn
            - name: Install packages
              run: yarn
            - name: Build
              run: yarn build
            - name: Test
              run: yarn frontend test

    lint:
        name: Lint
        runs-on: ubuntu-22.04
        timeout-minutes: 10
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Install node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16'
            - name: Install packages
              run: yarn
            - name: Lint
              run: |
                  yarn lint:fix
                  yarn lint:check
