name: isntall-circom

on:
  push:
    branches:
      - main

jobs:
  node-version:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Install Circom
      run: |
        curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
        source "$HOME/.cargo/env"
        cd /tmp
        git clone https://github.com/iden3/circom.git
        cd circom
        cargo build --release
        cargo install --path circom