name: node-version

on:
  push:
    branches:
      - main

jobs:
  node-version:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Set node version
      run: |
        nvm install v16
        nvm alias default v16
        echo "nvm use default" >> $BASH_ENV

    - name: Check node version
      run: node -v | grep v16
  